apiVersion: v1
kind: Secret
metadata:
  name: keda-aws-secrets
stringData:
  AWS_ACCESS_KEY_ID: put-access-key-id-here # Required.
  AWS_SECRET_ACCESS_KEY: put-secret-here # Required.
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID     # Required.
    name: keda-aws-secrets        # Required.
    key: AWS_ACCESS_KEY_ID        # Required.
  - parameter: awsSecretAccessKey # Required.
    name: keda-aws-secrets        # Required.
    key: AWS_SECRET_ACCESS_KEY    # Required.
